# Generated by Django 6.0.3 on 2026-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free'),
            preserve_default=False,
        ),
    ]
