# Generated by Django 6.0.3 on 2026-03-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0002_trending_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
