# Generated by Django 6.0.3 on 2026-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0003_trending_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')]),
        ),
    ]
