# Generated by Django 6.0.3 on 2026-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0004_trending_url_alter_trending_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
