# Generated by Django 6.0.3 on 2026-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0005_frontend_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_ai',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
