# Generated by Django 6.0.3 on 2026-03-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0006_alter_frontend_ai_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backend_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devops_Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testing_Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UI_UX_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Freemium', 'Freemium')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='frontend_ai',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
